
TYPO3:
  TypoScript:
    defaultContext:
      Networkteam.Neos.Util.Format.SanitizedId: Networkteam\Neos\Util\String\StringToIdSanitizer
Networkteam:
  Neos:
    Util:
      locales: 'de_DE.utf8,de_DE,de'
Neos:
  Neos:
    typoScript:
      autoInclude:
        Networkteam.Neos.Util: true
