
Networkteam:
  Neos:
    Util:
      locales: 'de_DE.utf8,de_DE,de'
Neos:
  Neos:
    fusion:
      autoInclude:
        Networkteam.Neos.Util: true
  Fusion:
    defaultContext:
      Networkteam.Neos.Util.Caching: Networkteam\Neos\Util\Eel\CachingHelper
      Networkteam.Neos.Util.Format.SanitizedId: Networkteam\Neos\Util\String\StringToIdSanitizer
